### ISSUE TITLE
Map CTRL+M to ENTER

### ISSUE THREAD

**Issue by jayache80** [tadosappo/nasskan#10]
I can't seem to get this software to work for me.

I'd simply like to remap CTRL+M to ENTER. In most terminal environments, and even some well-behaving GUI apps, CTRL+M _is_ ENTER. However, in Firefox, CTRL+M toggles Mute, which is never what I want.

So I was hoping nasskan can solve my problem, and seems like a very achievable use case.

This is the config I tried:
```
version: 1
devices:
  - if:
      ID_VENDOR_ID: 04d9
      ID_MODEL_ID: a131
    then:
      - from:
          key: M
          with:
            - LEFTCTRL
        to:
          key: ENTER
```

Alas, it doesn't work. It makes the M key by itself unresponsive, and CTRL+M doesn't do anything either.

Do you see any user error?

By the way, the README.md has a `device` key, but it should be `devices`.
