### ISSUE TITLE
Nasskan works (to map RIGHTALT to LEFTMETA), but while it's running my ENTER key no longer works.

### ISSUE THREAD

**Issue by thomas-profitt** [tadosappo/nasskan#11]
Nasskan looks like exactly the interface I think keyboard remapping in Wayland should have.
I'm having a strange issue though.

I have two keyboards plugged in, one modern custom keyboard connected via USB and one old Model M connected via PS/2.
The Model M doesn't have a Meta key, so I'm using Nasskan to remap its RIGHTALT to LEFTMETA.

Here's my config:
```yaml
---
version: 1
devices:
  - if:
      ID_INPUT_KEYBOARD: 1
      ID_BUS: i8042
    then:
      - from:
          key: LEFTALT
        to:
          key: LEFTMETA
```

When Nasskan is running, it correctly remaps LEFTALT on the Model M and not the USB keyboard, as expected, but something strange happens: the ENTER keys of both keyboards stop working. The KPENTER key on the Model M still works. All other keys still work.

Nasskan's debug logs show the same output when ENTER or KPENTER is pressed, but only KPENTER works and ENTER on both boards does nothing. When I stop Nasskan, they start working again.

This workaround circumvents the problem by remapping ENTER to KPENTER:
```yaml
      - from:
          key: ENTER
        to:
          key: KPENTER
```

What might be happening? Can anyone reproduce this? How can I help debug this?
